# Generated by Django 4.2.2 on 2023-06-26 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='not added', max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.companyprofile')),
            ],
        ),
    ]
