# Generated by Django 4.0 on 2023-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.FileField(default='path/to/default_resume.pdf', upload_to='resumes/'),
        ),
    ]
